import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'id';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.order': 'Order',
    
    // Landing Page
    'landing.title': 'JOKIMIL',
    'landing.subtitle': 'Personal Wuthering Waves Boosting Service',
    'landing.description': 'Run by a dedicated player, for players',
    'landing.personal': 'Personal Service',
    'landing.fast': 'Fast Delivery',
    'landing.safe': '100% Safe',
    'landing.whatsapp': 'WhatsApp Support',
    'landing.cta.boost': 'Get Boosted Now',
    'landing.cta.whatsapp': 'WhatsApp Me',
    'landing.stats.orders': 'Orders Completed',
    'landing.stats.satisfaction': 'Customer Satisfaction',
    'landing.stats.support': 'WhatsApp Support',
    'landing.stats.safety': 'Account Safety',
    'landing.why.title': 'Why Choose Jokimil?',
    'landing.why.subtitle': 'Experience personalized boosting service with direct communication and guaranteed results',
    'landing.feature.safe.title': '100% Safe',
    'landing.feature.safe.desc': 'Your account security is my top priority. I never use cheats or bots.',
    'landing.feature.fast.title': 'Fast Delivery',
    'landing.feature.fast.desc': 'Most orders completed within 24-48 hours by me personally.',
    'landing.feature.personal.title': 'Personal Service',
    'landing.feature.personal.desc': 'Direct communication with me - no middlemen, no delays.',
    'landing.feature.available.title': 'Always Available',
    'landing.feature.available.desc': 'Contact me anytime on WhatsApp for instant support and updates.',
    'landing.services.title': 'My Services',
    'landing.services.subtitle': 'Affordable boosting solutions with personal attention',
    'landing.services.view': 'View All Services',
    'landing.personal.title': 'Personal Service',
    'landing.personal.desc': 'Unlike large boosting companies, you\'re dealing directly with me. I personally handle every order, ensuring quality and building trust with each client.',
    'landing.personal.direct': 'Direct communication via WhatsApp',
    'landing.personal.attention': 'Personal attention to every order',
    'landing.personal.flexible': 'Flexible scheduling and requirements',
    'landing.personal.updates': 'Real-time updates and progress reports',
    'landing.personal.greeting': 'Hi, I\'m Jokimil!',
    'landing.personal.role': 'Your personal Wuthering Waves booster',
    'landing.personal.quote': '"I started this service because I love helping fellow players achieve their goals. Every account I work on gets my full attention and care."',
    'landing.testimonials.title': 'What My Clients Say',
    
    // Services
    'service.map': 'Map Unlocking',
    'service.map.desc': 'Unlock all areas and waypoints',
    'service.echo': 'Echo Farming',
    'service.echo.desc': 'Farm rare echoes efficiently',
    'service.quest': 'Main Quest Completion',
    'service.quest.desc': 'Complete story missions',
    'service.boss': 'Weekly Boss Runs',
    'service.boss.desc': 'Defeat weekly bosses for rewards',
    'service.stream': 'Live Stream Option',
    'service.stream.desc': 'Watch me work on your account',
    'service.priority': 'Priority Order',
    'service.priority.desc': 'Jump the queue for faster completion',
    
    // About Page
    'about.title': 'About Jokimil',
    'about.subtitle': 'Hi! I\'m the founder and sole operator of Jokimil. As a passionate Wuthering Waves player, I started this service to help fellow gamers achieve their goals safely and efficiently. Every order gets my personal attention and expertise.',
    'about.founded': 'Founded',
    'about.approach.title': 'My Approach',
    'about.approach.subtitle': 'What makes my service different from the rest',
    'about.value.personal.title': 'Personal Touch',
    'about.value.personal.desc': 'As a solo operator and passionate Wuthering Waves player, I personally handle every order with dedication and expertise. You\'re not just a number - you get my full attention.',
    'about.value.safety.title': 'Account Safety First',
    'about.value.safety.desc': 'I use only legitimate gameplay methods and never employ cheats, hacks, or bots. Your account\'s integrity and security are my top priorities, with a 100% safety guarantee.',
    'about.value.manual.title': 'Manual Play Only',
    'about.value.manual.desc': 'Every order is completed through manual gameplay by me personally. I strictly prohibit the use of automation tools or cheating software to protect your account from any risk.',
    'about.value.communication.title': 'Direct Communication',
    'about.value.communication.desc': 'Communicate directly with me through WhatsApp for instant updates, questions, and support. No middlemen, no delays - just direct, personal service.',
    'about.value.quick.title': 'Quick Fulfillment',
    'about.value.quick.desc': 'As a dedicated solo operator, I focus entirely on your order without distractions. Most orders are completed within 24-48 hours, often faster than expected.',
    'about.value.privacy.title': 'Privacy Protection',
    'about.value.privacy.desc': 'Your personal information and account details are handled with utmost care. I never share your data and delete all information after order completion.',
    'about.work.title': 'How I Work',
    'about.work.subtitle': 'My proven process ensures maximum efficiency and security',
    'about.work.step1.title': 'WhatsApp Contact',
    'about.work.step1.desc': 'Message me on WhatsApp with your desired service and I\'ll respond quickly with details.',
    'about.work.step2.title': 'Order Discussion',
    'about.work.step2.desc': 'We discuss your specific needs, timeline, and I provide you with a personalized quote.',
    'about.work.step3.title': 'Secure Boosting',
    'about.work.step3.desc': 'I personally work on your account using only manual gameplay methods with regular updates.',
    'about.work.step4.title': 'Completion',
    'about.work.step4.desc': 'You receive notification when complete, with detailed progress reports and screenshots.',
    'about.me.title': 'About Me',
    'about.me.subtitle': 'The person behind Jokimil',
    'about.me.name': 'Jokimil - Founder & Operator',
    'about.me.desc': 'I\'m a dedicated Wuthering Waves enthusiast who has been playing since launch. After helping friends with their accounts, I realized there was a need for a trustworthy, personal boosting service. I founded Jokimil to provide safe, reliable boosting with a personal touch that larger services can\'t match.',
    'about.me.experience': 'Experience',
    'about.me.experience.value': '2+ Years Playing',
    'about.me.specialty': 'Specialty',
    'about.me.specialty.value': 'All Content Types',
    'about.me.approach': 'Approach',
    'about.me.approach.value': 'Personal & Safe',
    'about.trust.title': 'Trust & Security',
    'about.trust.subtitle': 'Your account security is my primary concern. I have never had a single account compromised and maintain the highest standards of security protocols.',
    'about.trust.manual.title': 'Manual Play Only',
    'about.trust.manual.desc': 'I personally play your account manually - no bots, no cheats, no automation.',
    'about.trust.secure.title': 'Secure Communication',
    'about.trust.secure.desc': 'All communication through WhatsApp with end-to-end encryption.',
    'about.trust.guarantee.title': 'Personal Guarantee',
    'about.trust.guarantee.desc': 'I stake my reputation on every order and personally guarantee your satisfaction.',
    'about.trust.contact.title': 'Direct Contact',
    'about.trust.contact.desc': 'Speak directly with me - no customer service reps, no delays.',
    'about.promise.title': 'My Promise',
    'about.promise.desc': 'I treat every account as if it were my own. Your progress, your items, your achievements - they all matter to me personally. If you\'re not completely satisfied, I\'ll make it right.',
    'about.promise.safety': '100% Account Safety',
    'about.promise.personal': 'Personal Service',
    'about.promise.direct': 'Direct Communication',
    
    // Order Page
    'order.title': 'Place Your Order',
    'order.subtitle': 'Select your desired services and contact me directly on WhatsApp. I\'ll handle everything personally with complete security and efficiency.',
    'order.select.title': 'Select Services',
    'order.select.subtitle': 'Choose the boosting services you need',
    'order.additional.title': 'Additional Options',
    'order.stream.title': 'Live Stream Progress',
    'order.stream.desc': 'Watch me work on your account in real-time via live stream. Perfect for transparency and learning!',
    'order.stream.feature': 'Real-time streaming during boost',
    'order.summary.title': 'Order Summary',
    'order.summary.empty': 'Select services to see your order summary',
    'order.summary.total': 'Total:',
    'order.summary.whatsapp': 'Order via WhatsApp',
    'order.why.title': 'Why Choose Me?',
    'order.why.safety': '100% Account Safety',
    'order.why.manual': 'Manual Play Only',
    'order.why.personal': 'Personal Service',
    'order.why.communication': 'Direct Communication',
    'order.how.title': 'How to Order',
    'order.how.subtitle': 'Simple steps to get your boosting started',
    'order.how.step1.title': 'Select Services',
    'order.how.step1.desc': 'Choose your desired boosting services and options above',
    'order.how.step2.title': 'Contact via WhatsApp',
    'order.how.step2.desc': 'Click the WhatsApp button to send me your order details',
    'order.how.step3.title': 'Get Boosted',
    'order.how.step3.desc': 'I\'ll handle everything personally and keep you updated',
    'order.communication.title': 'Direct Communication',
    'order.communication.desc': 'I prefer WhatsApp for orders because it allows for instant communication, secure messaging, and real-time updates throughout your boosting process.',
    'order.communication.instant': 'Instant Responses',
    'order.communication.secure': 'Secure Messaging',
    'order.communication.realtime': 'Real-time Updates',
    'order.faq.title': 'Frequently Asked Questions',
    'order.faq.q1': 'How long does the boosting process take?',
    'order.faq.a1': 'Most orders are completed within 24-48 hours. Priority orders are finished 50% faster. I\'ll give you a more specific timeline when we discuss your order.',
    'order.faq.q2': 'Is my account safe during the boosting process?',
    'order.faq.a2': 'Absolutely. I use only manual gameplay methods and never use cheats or bots. Your account security is my top priority, and I\'ve never had an account compromised.',
    'order.faq.q3': 'What\'s the live stream option?',
    'order.faq.a3': 'For an extra $10, I can stream the boosting process live so you can watch me work on your account in real-time. It\'s great for transparency and learning!',
    'order.faq.q4': 'How do I pay for the service?',
    'order.faq.a4': 'We\'ll discuss payment methods when you contact me on WhatsApp. I accept various secure payment options and we\'ll arrange what works best for you.',
    
    // Footer
    'footer.tagline': 'Personal Wuthering Waves boosting service run by a dedicated player who cares about your progress.',
    'footer.status': 'Personal • Safe • Affordable',
    'footer.links': 'Quick Links',
    'footer.services': 'Services',
    'footer.contact': 'Contact Me',
    'footer.whatsapp': 'WhatsApp Available',
    'footer.response': 'Quick Response Time',
    'footer.personal': 'Personal Service',
    'footer.safe': '100% Safe',
    'footer.copyright': '© 2024 Jokimil. Personal Wuthering Waves boosting service.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.refund': 'Refund Policy',
    
    // Testimonials
    'testimonial.1.name': 'Alex Chen',
    'testimonial.1.text': 'Amazing personal service! Jokimil kept me updated throughout and delivered exactly what was promised.',
    'testimonial.2.name': 'Sarah Kim',
    'testimonial.2.text': 'Finally found a booster who actually cares about the work. Great communication via WhatsApp!',
    'testimonial.3.name': 'Mike Rodriguez',
    'testimonial.3.text': 'Fast, safe, and affordable. The live stream option was awesome - got to watch and learn!',
    
    // Service Details
    'service.map.full': 'Unlock all areas, waypoints, and exploration points',
    'service.echo.full': 'Farm rare and legendary echoes efficiently',
    'service.quest.full': 'Complete main story missions and side quests',
    'service.boss.full': 'Complete weekly boss challenges for rare rewards',
    'service.safety.title': 'Account Safety Add-on',
    'service.safety.desc': 'Extra security measures and manual play guarantee',
    'service.duration.6-12': '6-12 hours',
    'service.duration.12-24': '12-24 hours',
    'service.duration.24-48': '24-48 hours',
    'service.duration.2-4': '2-4 hours',
    'service.duration.none': 'No additional time',
    'service.duration.faster': '50% faster',
  },
  id: {
    // Navigation
    'nav.home': 'Beranda',
    'nav.about': 'Tentang',
    'nav.order': 'Pesan',
    
    // Landing Page
    'landing.title': 'JOKIMIL',
    'landing.subtitle': 'Layanan Boosting Wuthering Waves Personal',
    'landing.description': 'Dijalankan oleh pemain berpengalaman, untuk para pemain',
    'landing.personal': 'Layanan Personal',
    'landing.fast': 'Pengiriman Cepat',
    'landing.safe': '100% Aman',
    'landing.whatsapp': 'Dukungan WhatsApp',
    'landing.cta.boost': 'Boost Sekarang',
    'landing.cta.whatsapp': 'WhatsApp Saya',
    'landing.stats.orders': 'Pesanan Selesai',
    'landing.stats.satisfaction': 'Kepuasan Pelanggan',
    'landing.stats.support': 'Dukungan WhatsApp',
    'landing.stats.safety': 'Keamanan Akun',
    'landing.why.title': 'Mengapa Pilih Jokimil?',
    'landing.why.subtitle': 'Rasakan layanan boosting personal dengan komunikasi langsung dan hasil terjamin',
    'landing.feature.safe.title': '100% Aman',
    'landing.feature.safe.desc': 'Keamanan akun Anda adalah prioritas utama saya. Saya tidak pernah menggunakan cheat atau bot.',
    'landing.feature.fast.title': 'Pengiriman Cepat',
    'landing.feature.fast.desc': 'Sebagian besar pesanan selesai dalam 24-48 jam oleh saya secara personal.',
    'landing.feature.personal.title': 'Layanan Personal',
    'landing.feature.personal.desc': 'Komunikasi langsung dengan saya - tanpa perantara, tanpa penundaan.',
    'landing.feature.available.title': 'Selalu Tersedia',
    'landing.feature.available.desc': 'Hubungi saya kapan saja di WhatsApp untuk dukungan dan update instan.',
    'landing.services.title': 'Layanan Saya',
    'landing.services.subtitle': 'Solusi boosting terjangkau dengan perhatian personal',
    'landing.services.view': 'Lihat Semua Layanan',
    'landing.personal.title': 'Layanan Personal',
    'landing.personal.desc': 'Tidak seperti perusahaan boosting besar, Anda berurusan langsung dengan saya. Saya menangani setiap pesanan secara personal, memastikan kualitas dan membangun kepercayaan dengan setiap klien.',
    'landing.personal.direct': 'Komunikasi langsung via WhatsApp',
    'landing.personal.attention': 'Perhatian personal untuk setiap pesanan',
    'landing.personal.flexible': 'Penjadwalan dan persyaratan yang fleksibel',
    'landing.personal.updates': 'Update real-time dan laporan progress',
    'landing.personal.greeting': 'Hai, saya Jokimil!',
    'landing.personal.role': 'Booster Wuthering Waves personal Anda',
    'landing.personal.quote': '"Saya memulai layanan ini karena saya suka membantu sesama pemain mencapai tujuan mereka. Setiap akun yang saya kerjakan mendapat perhatian penuh dan perawatan saya."',
    'landing.testimonials.title': 'Apa Kata Klien Saya',
    
    // Services
    'service.map': 'Buka Kunci Peta',
    'service.map.desc': 'Buka semua area dan waypoint',
    'service.echo': 'Farming Echo',
    'service.echo.desc': 'Farm echo langka secara efisien',
    'service.quest': 'Penyelesaian Quest Utama',
    'service.quest.desc': 'Selesaikan misi cerita',
    'service.boss': 'Weekly Boss Run',
    'service.boss.desc': 'Kalahkan weekly boss untuk reward',
    'service.stream': 'Opsi Live Stream',
    'service.stream.desc': 'Tonton saya bekerja di akun Anda',
    'service.priority': 'Pesanan Prioritas',
    'service.priority.desc': 'Lewati antrian untuk penyelesaian lebih cepat',
    
    // About Page
    'about.title': 'Tentang Jokimil',
    'about.subtitle': 'Hai! Saya adalah pendiri dan operator tunggal Jokimil. Sebagai pemain Wuthering Waves yang bersemangat, saya memulai layanan ini untuk membantu sesama gamer mencapai tujuan mereka dengan aman dan efisien. Setiap pesanan mendapat perhatian personal dan keahlian saya.',
    'about.founded': 'Didirikan',
    'about.approach.title': 'Pendekatan Saya',
    'about.approach.subtitle': 'Apa yang membuat layanan saya berbeda dari yang lain',
    'about.value.personal.title': 'Sentuhan Personal',
    'about.value.personal.desc': 'Sebagai operator tunggal dan pemain Wuthering Waves yang bersemangat, saya menangani setiap pesanan secara personal dengan dedikasi dan keahlian. Anda bukan hanya nomor - Anda mendapat perhatian penuh saya.',
    'about.value.safety.title': 'Keamanan Akun Utama',
    'about.value.safety.desc': 'Saya hanya menggunakan metode gameplay yang sah dan tidak pernah menggunakan cheat, hack, atau bot. Integritas dan keamanan akun Anda adalah prioritas utama saya, dengan jaminan keamanan 100%.',
    'about.value.manual.title': 'Hanya Main Manual',
    'about.value.manual.desc': 'Setiap pesanan diselesaikan melalui gameplay manual oleh saya secara personal. Saya sangat melarang penggunaan alat otomasi atau software cheat untuk melindungi akun Anda dari risiko apapun.',
    'about.value.communication.title': 'Komunikasi Langsung',
    'about.value.communication.desc': 'Berkomunikasi langsung dengan saya melalui WhatsApp untuk update instan, pertanyaan, dan dukungan. Tanpa perantara, tanpa penundaan - hanya layanan langsung dan personal.',
    'about.value.quick.title': 'Pemenuhan Cepat',
    'about.value.quick.desc': 'Sebagai operator tunggal yang berdedikasi, saya fokus sepenuhnya pada pesanan Anda tanpa gangguan. Sebagian besar pesanan selesai dalam 24-48 jam, seringkali lebih cepat dari yang diharapkan.',
    'about.value.privacy.title': 'Perlindungan Privasi',
    'about.value.privacy.desc': 'Informasi personal dan detail akun Anda ditangani dengan sangat hati-hati. Saya tidak pernah membagikan data Anda dan menghapus semua informasi setelah pesanan selesai.',
    'about.work.title': 'Cara Kerja Saya',
    'about.work.subtitle': 'Proses terbukti saya memastikan efisiensi dan keamanan maksimum',
    'about.work.step1.title': 'Kontak WhatsApp',
    'about.work.step1.desc': 'Kirim pesan kepada saya di WhatsApp dengan layanan yang Anda inginkan dan saya akan merespons dengan cepat dengan detail.',
    'about.work.step2.title': 'Diskusi Pesanan',
    'about.work.step2.desc': 'Kami mendiskusikan kebutuhan spesifik Anda, timeline, dan saya memberikan Anda penawaran yang dipersonalisasi.',
    'about.work.step3.title': 'Boosting Aman',
    'about.work.step3.desc': 'Saya secara personal bekerja di akun Anda menggunakan hanya metode gameplay manual dengan update reguler.',
    'about.work.step4.title': 'Penyelesaian',
    'about.work.step4.desc': 'Anda menerima notifikasi ketika selesai, dengan laporan progress detail dan screenshot.',
    'about.me.title': 'Tentang Saya',
    'about.me.subtitle': 'Orang di balik Jokimil',
    'about.me.name': 'Jokimil - Pendiri & Operator',
    'about.me.desc': 'Saya adalah penggemar Wuthering Waves yang berdedikasi yang telah bermain sejak peluncuran. Setelah membantu teman-teman dengan akun mereka, saya menyadari ada kebutuhan untuk layanan boosting yang dapat dipercaya dan personal. Saya mendirikan Jokimil untuk menyediakan boosting yang aman dan dapat diandalkan dengan sentuhan personal yang tidak bisa ditandingi layanan besar.',
    'about.me.experience': 'Pengalaman',
    'about.me.experience.value': '2+ Tahun Bermain',
    'about.me.specialty': 'Spesialisasi',
    'about.me.specialty.value': 'Semua Jenis Konten',
    'about.me.approach': 'Pendekatan',
    'about.me.approach.value': 'Personal & Aman',
    'about.trust.title': 'Kepercayaan & Keamanan',
    'about.trust.subtitle': 'Keamanan akun Anda adalah perhatian utama saya. Saya tidak pernah memiliki satu akun pun yang dikompromikan dan mempertahankan standar protokol keamanan tertinggi.',
    'about.trust.manual.title': 'Hanya Main Manual',
    'about.trust.manual.desc': 'Saya secara personal memainkan akun Anda secara manual - tanpa bot, tanpa cheat, tanpa otomasi.',
    'about.trust.secure.title': 'Komunikasi Aman',
    'about.trust.secure.desc': 'Semua komunikasi melalui WhatsApp dengan enkripsi end-to-end.',
    'about.trust.guarantee.title': 'Jaminan Personal',
    'about.trust.guarantee.desc': 'Saya mempertaruhkan reputasi saya pada setiap pesanan dan secara personal menjamin kepuasan Anda.',
    'about.trust.contact.title': 'Kontak Langsung',
    'about.trust.contact.desc': 'Berbicara langsung dengan saya - tanpa customer service, tanpa penundaan.',
    'about.promise.title': 'Janji Saya',
    'about.promise.desc': 'Saya memperlakukan setiap akun seolah-olah itu milik saya sendiri. Progress Anda, item Anda, pencapaian Anda - semuanya penting bagi saya secara personal. Jika Anda tidak sepenuhnya puas, saya akan membuatnya benar.',
    'about.promise.safety': '100% Keamanan Akun',
    'about.promise.personal': 'Layanan Personal',
    'about.promise.direct': 'Komunikasi Langsung',
    
    // Order Page
    'order.title': 'Buat Pesanan Anda',
    'order.subtitle': 'Pilih layanan yang Anda inginkan dan hubungi saya langsung di WhatsApp. Saya akan menangani semuanya secara personal dengan keamanan dan efisiensi lengkap.',
    'order.select.title': 'Pilih Layanan',
    'order.select.subtitle': 'Pilih layanan boosting yang Anda butuhkan',
    'order.additional.title': 'Opsi Tambahan',
    'order.stream.title': 'Progress Live Stream',
    'order.stream.desc': 'Tonton saya bekerja di akun Anda secara real-time melalui live stream. Sempurna untuk transparansi dan pembelajaran!',
    'order.stream.feature': 'Streaming real-time selama boost',
    'order.summary.title': 'Ringkasan Pesanan',
    'order.summary.empty': 'Pilih layanan untuk melihat ringkasan pesanan Anda',
    'order.summary.total': 'Total:',
    'order.summary.whatsapp': 'Pesan via WhatsApp',
    'order.why.title': 'Mengapa Pilih Saya?',
    'order.why.safety': '100% Keamanan Akun',
    'order.why.manual': 'Hanya Main Manual',
    'order.why.personal': 'Layanan Personal',
    'order.why.communication': 'Komunikasi Langsung',
    'order.how.title': 'Cara Memesan',
    'order.how.subtitle': 'Langkah sederhana untuk memulai boosting Anda',
    'order.how.step1.title': 'Pilih Layanan',
    'order.how.step1.desc': 'Pilih layanan boosting dan opsi yang Anda inginkan di atas',
    'order.how.step2.title': 'Kontak via WhatsApp',
    'order.how.step2.desc': 'Klik tombol WhatsApp untuk mengirim detail pesanan Anda kepada saya',
    'order.how.step3.title': 'Dapatkan Boost',
    'order.how.step3.desc': 'Saya akan menangani semuanya secara personal dan memberi Anda update',
    'order.communication.title': 'Komunikasi Langsung',
    'order.communication.desc': 'Saya lebih suka WhatsApp untuk pesanan karena memungkinkan komunikasi instan, pesan aman, dan update real-time sepanjang proses boosting Anda.',
    'order.communication.instant': 'Respon Instan',
    'order.communication.secure': 'Pesan Aman',
    'order.communication.realtime': 'Update Real-time',
    'order.faq.title': 'Pertanyaan yang Sering Diajukan',
    'order.faq.q1': 'Berapa lama proses boosting berlangsung?',
    'order.faq.a1': 'Sebagian besar pesanan selesai dalam 24-48 jam. Pesanan prioritas selesai 50% lebih cepat. Saya akan memberi Anda timeline yang lebih spesifik ketika kita mendiskusikan pesanan Anda.',
    'order.faq.q2': 'Apakah akun saya aman selama proses boosting?',
    'order.faq.a2': 'Tentu saja. Saya hanya menggunakan metode gameplay manual dan tidak pernah menggunakan cheat atau bot. Keamanan akun Anda adalah prioritas utama saya, dan saya tidak pernah memiliki akun yang dikompromikan.',
    'order.faq.q3': 'Apa itu opsi live stream?',
    'order.faq.a3': 'Dengan tambahan $10, saya dapat streaming proses boosting secara langsung sehingga Anda dapat menonton saya bekerja di akun Anda secara real-time. Bagus untuk transparansi dan pembelajaran!',
    'order.faq.q4': 'Bagaimana cara saya membayar layanan ini?',
    'order.faq.a4': 'Kita akan mendiskusikan metode pembayaran ketika Anda menghubungi saya di WhatsApp. Saya menerima berbagai opsi pembayaran aman dan kita akan mengatur apa yang terbaik untuk Anda.',
    
    // Footer
    'footer.tagline': 'Layanan boosting Wuthering Waves personal yang dijalankan oleh pemain berpengalaman yang peduli dengan progress Anda.',
    'footer.status': 'Personal • Aman • Terjangkau',
    'footer.links': 'Link Cepat',
    'footer.services': 'Layanan',
    'footer.contact': 'Hubungi Saya',
    'footer.whatsapp': 'WhatsApp Tersedia',
    'footer.response': 'Waktu Respon Cepat',
    'footer.personal': 'Layanan Personal',
    'footer.safe': '100% Aman',
    'footer.copyright': '© 2024 Jokimil. Layanan boosting Wuthering Waves personal.',
    'footer.privacy': 'Kebijakan Privasi',
    'footer.terms': 'Syarat Layanan',
    'footer.refund': 'Kebijakan Refund',
    
    // Testimonials
    'testimonial.1.name': 'Alex Chen',
    'testimonial.1.text': 'Layanan personal yang luar biasa! Jokimil memberi saya update sepanjang waktu dan memberikan persis seperti yang dijanjikan.',
    'testimonial.2.name': 'Sarah Kim',
    'testimonial.2.text': 'Akhirnya menemukan booster yang benar-benar peduli dengan pekerjaannya. Komunikasi yang bagus via WhatsApp!',
    'testimonial.3.name': 'Mike Rodriguez',
    'testimonial.3.text': 'Cepat, aman, dan terjangkau. Opsi live stream sangat keren - bisa menonton dan belajar!',
    
    // Service Details
    'service.map.full': 'Buka kunci semua area, waypoint, dan titik eksplorasi',
    'service.echo.full': 'Farm echo langka dan legendary secara efisien',
    'service.quest.full': 'Selesaikan misi cerita utama dan side quest',
    'service.boss.full': 'Selesaikan tantangan weekly boss untuk reward langka',
    'service.safety.title': 'Add-on Keamanan Akun',
    'service.safety.desc': 'Langkah keamanan ekstra dan jaminan main manual',
    'service.duration.6-12': '6-12 jam',
    'service.duration.12-24': '12-24 jam',
    'service.duration.24-48': '24-48 jam',
    'service.duration.2-4': '2-4 jam',
    'service.duration.none': 'Tanpa waktu tambahan',
    'service.duration.faster': '50% lebih cepat',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};